### ISSUE TITLE
(Empty) map displays in directory channel

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_directories#229]
Steps to reproduce: 

1. add a directory channel
2. add promo pages
3. visit channel 
4. see an empty map

**Comment by ekes** [comment]
Argh.

So the map gets hidden if there are no results. But there are results they just don't have a location. But we can't filter on them having a location, because that's not indexed by Search API (guess we'd need Adnan's patch to do that, and it's not consistent for all versions of MySQL).

The features are put into the attachment of the render array. So you can't hide the map based on if they are there, because it's not available in the render. There are alter hooks but they still put a map element in.

Patching the module is the easiest, but this is such an edge case I can't see the patch going in.

Adding _something_ to the index that can be filtered on seems one option. 
Somehow getting some data to the map that it has features so it can be hidden in the theme seems to be the other.
