### ISSUE TITLE
Directorty entries not filtered by channel [Fresh install, demo content]

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_directories#238]
Just did a new spin up of localgov_directories with `composer install; drush si localgov -y; drush en localgov_demo -y`
and spotted that the directory channel Money, employment and training is showing national parks and localgov collaborators too.

Might be a demo content issue, it seems some entries arn't assigned to a directory, but worth checking if fresh installs arn't getting filtered correctly.

<img width="1336" alt="Screenshot 2022-10-06 at 12 07 33 pm" src="https://user-images.githubusercontent.com/1467480/194298445-04cc4a8b-22c6-4b0c-8830-6506045ea89d.png">

**Comment by ekes** [comment]
A views filter, and the additional fields on the index, were broken for new installs until https://github.com/localgovdrupal/localgov_directories/pull/233

Is it possible to check that (a) it installed with the version that includes that (b) that the channels field is on the index. If so I suspect it'll be a demo content issue. **edit** or maybe in needs a re-index? Because the content may well have gone in while there was an index without the channels field, which then gets added?

**Comment by andybroomfield** [comment]
I had the branch for #235 checked out, I assume that was before the fix.
However I'm still seeing some parks on the money directory, no mixes on the others and the views contextual filter is present. 
It looks like a demo content issue, as when I assign them the correct channel they appear there.
Rebuilding the search index fixes the issue, bit strange the money one was the one they where on. 
I think this is a demo content issue though so I will raise an issue there.
