### ISSUE TITLE
Directories 2.5 upgrade overwriting directories view customisations

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_directories#280]
Now that #278 fixes the upgrade so old optional config is no longer reinstalled, we've encountered a new issue with the localgov_directory_channel view displays getting overwritten to accomodate the new location search, removing any customisations.

Whilst not super major (We added a custom class and changed the display mode of the rendered items), it is something that should be avoided if possible. I know its needed to support the new proximity search filter, so would a more fine grained import be possible? If not, perhaps it better to document that a new view / or filter needs to be set up and if as a last resort config needs to be overwritten that this is documented in release notes. [2.5.0 notes for reference](https://github.com/localgovdrupal/localgov_directories/releases/tag/2.5.0)

BHCC makes use of [config distro](https://www.drupal.org/project/config_distro) to allow for merging config updates non-destructivly and is our preffered way of getting the updates. Appreciate thats not to everyones taste but it will mean writng less config update hooks. :-)

**Comment by andybroomfield** [comment]
This is the [code](https://github.com/localgovdrupal/localgov_directories/blob/99dc8113d91cbddeb4610655fc0591daff4fb4aa/modules/localgov_directories_location/src/ProximitySearchSetup.php#L144) that overwrites the view.
````php
  /**
   * Adds the Proximity search display to the Directory channel view.
   *
   * Also adds the Proximity search filter to the existing Map display of this
   * view.
   */
  public function addViewsDisplay(): void {

    $view = $this->etm->getStorage('view')->load(Directory::CHANNEL_VIEW);
    if (empty($view) || $view->getDisplay(Directory::CHANNEL_VIEW_PROXIMITY_SEARCH_DISPLAY)) {
      return;
    }

    $view_with_proximity_search = Yaml::decode(file_get_contents($this->modulePath . '/config/override/views.view.localgov_directory_channel.yml'));

    $displays = $view->get('display');
    $displays[Directory::CHANNEL_VIEW_PROXIMITY_SEARCH_DISPLAY] = $view_with_proximity_search['display'][Directory::CHANNEL_VIEW_PROXIMITY_SEARCH_DISPLAY];
    $displays[Directory::CHANNEL_VIEW_MAP_DISPLAY] = $view_with_proximity_search['display'][Directory::CHANNEL_VIEW_MAP_DISPLAY];
    $view->set('display', $displays);
    $view->save();
  }
````
and the diff of the changes it made to our install (as mentioned, they are minor enough that we can address ourselves).

[views.view.localgov_directory_channel.yml.patch](https://github.com/localgovdrupal/localgov_directories/files/11271575/views.view.localgov_directory_channel.yml.patch)

**Comment by ekes** [comment]
Think I should have picked this up in review.

We do control the _initial_ creation of the views, because that's the idea of the directories thing, it auto configures itself.

However, any updates we so far haven't pushed without making a check for any changes that could get overriden. Then just skipping, and sending a message to the user that the skip has been made. Like I've myself made quite substantial changes to directories views!

**Comment by andybroomfield** [comment]
Thanks @ekes thats good to know. Do we need to do anything here or is it just a documentation fix? I guess most will have run the update by now. As I said, I know how to reset what we had so we can reset this ourselves.

**Comment by ekes** [comment]
I do think we should update the code to make a altered check before doing anything none the less.

**Comment by andybroomfield** [comment]
@ekes Did you get anywhere with this. Just at the moment havn't been able to upgrade BHCC to 2.5+ and wondering if I should go ahead and reset the view afterwards.

**Comment by stephen-cox** [comment]
This seems to be the first major test of our update policy: https://github.com/localgovdrupal/localgov/wiki/Developers:-Updates#configuration

We need decide how to test for config changes. The YAML config files will have changed so it probably makes sense to hard code the old config in the update hook, but we could create a config dir for old YAML config files indexed by update hook number.

We also need to agree what and how to display a message to the user when the new config isn't applied. I suppose this will have to be done by returning the message from the update hook as it shouldn't result in an error. Would be nice to be able to display warning messages, but this doesn't look possible.

Finally, any code that depends on the new configuration will have to test this exists. It would be nice if there are tests for this so that future code changes that don't do this are caught early.

@andybroomfield If you want to update directories before any of this is done then you should be fine reverting the view after. I think we'll have to implement all of this at some point, but it's a bit of work, so may time a little while to get done.

**Comment by andybroomfield** [comment]
This issue is passed now so I will close it. Although the bug is still present for anyone updating pre 2.5 to any current version. I'm guessing BHCC was the only one who had done customisation work to encounter it. Have raised a new issue https://github.com/localgovdrupal/localgov/issues/773 so we can discuss ways forward on future module config updates.
