### ISSUE TITLE
Back end: Address fields don't complete automatically

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#90]
Create a directory venue page at https://localgovdrupal.agile.coop/node/add/localgov_directories_venue

Go to the venue tab

Enter any postcode eg BN21 4EQ

Helper text on the address fields:

"Should be filled in automatically on submission by the map search. If for any reason this fails you can complete it manually here."

The address isn't filled in automatically on submission of the map fields - it hasn't ever worked for me

**Comment by ekes** [comment]
Part of this work is here https://github.com/localgovdrupal/localgov_geo/pull/11

To make the geocoding UX better.

But in the end if it geocodes a postcode depends on the geocoder used. OpenstreetMap Nominatim is the default geocoder because it works without configuration for small number of queries - unlike every other alternative. However thanks to the privatization/ownership of postcodes it has very little postcode data in the UK. If a site changes to Google for example (requires changing api keys, the maps that are used, terms of service etc. stuff that we can't do out of the box in the distro) it should automatically do the postcode.

**Comment by willguv** [comment]
Thanks @ekes. Sounds like we can’t do anything else with this - shall I close it?

**Comment by willguv** [comment]
Or we could change the wording slightly….

“These fields are often completed automatically, depending on the type of maps you’re using. If this does not work, you can enter an address manually.”

**Comment by ekes** [comment]
I think there are usability improvements to make hence localgovdrupal/localgov_geo#11 With that you enter the address rather than auto completing it, and then press a button to 'look it up', it allows for more feedback.

In addition I think we can do something to make it clearer to the people setting up the site.

So lets leave this open, at least as long as the one on LocalGov Geo is open as a reminder something needs doing.

**Comment by andybroomfield** [comment]
We're currently looking at using our local geo data service, we did do an experimental geocoder plugin, and we're currently looking at it again for use in our webforms. 

We are able to do postcode searches for anything within Brighton, assuming you have simmilar data you should be able to build a geocoder plugin (it depends on your backend as we have a Mendix app to bridge the gap)

**Comment by willguv** [comment]
Let's consider new wording based on the map types you're using

**Comment by ekes** [comment]
So this has all be reworked with the autocomplete addressfield.
