### ISSUE TITLE
Discovery: Open Referral standard

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#92]
We've a long standing commitment to explore this standard and implement it on content that's appropriate - mainly around community/ self help services

Ryan and I are exploring this - details to follow

**Comment by RyanFH257** [comment]
I've reached out to Mike Thacker about meeting up to discuss how we can implement the standard. But I've picked this up from the forum on the Open Referral UK website:

From our [main website](https://openreferraluk.org/), go to [For developers 1](https://developers.openreferraluk.org/). From there, the Data standard | [Guidance 1](https://developers.openreferraluk.org/Guidance/) page shows the data structure as a diagram and in text form. There’s a lot in it, but very little is mandated.

The API | [Guidance](https://developers.openreferraluk.org/API-Guidance/) page describes the Application Programming Interface and links to [Swagger content](https://api.porism.com/ServiceDirectoryService/swagger-ui.html) which describes each web method.

The most important web methods are [the GET methods for services](https://api.porism.com/ServiceDirectoryService/swagger-ui.html#/Services), particularly:

- /services - returning a paginated list of services
- /services/{id} - returning full details of one identified services

The API Query tool shows examples of these calls with live API endpoints (plus calls to return vocabularies/taxonomies and their terms which can be used to filter a list of services).

**Comment by willguv** [comment]
Thanks @RyanFH257

**Comment by willguv** [comment]
Possible meeting with Mike this Friday 28th at 3.30 to answer any tech questions

**Comment by finnlewis** [comment]
@willguv would like us to start with a technical review of this ahead of a meeting with Mike Thacker.

Passing to @ekes for an initial review. 

Probably just a few hours initially before deciding what's next.

**Comment by ekes** [comment]
The one change _required_ for implementing the standard will be adding 'organisation' to the entity relationships.
There are further changes that can be implemented, but this can be incremental.

'Organisation' in the first instance is the organisation offering the 'Service' (for example the Council, or School, or Child Minders etc.) It is also used for Reviewers (for example Ofsted).

My initial proposal would be to create an Entity type for Organisation, and allow this to be selected, and created, as a Free Tagging Taxonomy, ie autocomplete field that will also make the entity if it doesn't exist. We Organisation we then serve for a service has but the minimum 'title' and 'id'.
This could be added to the existing Venue and Entry. It does rather beg the question if a if 'Venue' exactly means a 'Service' and if it we wouldn't be better creating a Open Referrer Service content type.
The other way of handling the Organisation, rather than make it a custom entity that doesn't do much, would be to make it a Directory Content Type itself; but then this would have to be properly created for every single service - like Childminder Organisation and Childminder Service.
The custom entity could be used for grouping - just as a Taxonomy Term - in the directory if desired. Using a custom entity makes it easier to keep this separate from different sorts of Terms - it could also allow bundles for 'Reviewer' for example, so Ofsted can be treated differently from a School. It could be extended to have more fields and its own special presentation if desired. It just wouldn't be a service entry in the directory itself, which seems to make sense.

With the simple Organisation, a Service, a Location, an Address presented with the required field names and relations we should meet a basic representation in the standard. The existing taxonomy terms can also be 'namespaced' as custom to the site itself. 

After that external controlled vocabularies could be added. Other entities like reviewer could be added etc.

**Comment by willguv** [comment]
Thanks @ekes this would have been a great chat for this week's story refinement (which we haven't got time to do)!

I can stay on at the end of tomorrow's stand up if you have time. Or we can park this here and pick up at next week's review. This isn't urgent, and there's plenty of other directories work to be getting on with.

Please let me know what works best for you.

**Comment by ekes** [comment]
Forgot about this yesterday. Monday or review...

**Comment by finnlewis** [comment]
Just to note, I've read your notes @ekes and I actually understand it! Brilliant! 

It would be really cool to be able to refactor directories to be able to work with the open referral standard. That would be a bit win-win-win I think.

**Comment by ekes** [comment]
Tickets:

 * The API endpoint https://github.com/localgovdrupal/localgov/issues/261 with WIP on `feature/2.x/261-POC-Open-Referral` branch and documented https://forum.openreferraluk.org/t/localgov-drupal-implementation/106 for feedback
 * https://github.com/localgovdrupal/localgov/issues/263 structural changes mentioned above.

**Comment by stephen-cox** [comment]
Done - sprint 3
